### ISSUE TITLE
Please make it build-able without projucer

### ISSUE THREAD

**Issue by magnetophon** [jerryuhoo/Fire#33]
This would make it possible to package it for source based distros.
I wuold like to package this for NixOS.

@baconpaul, You have done this a couple of times for other plugins, would you mind taking a look, or giving some advice?

**Comment by baconpaul** [comment]
There’s a cmakelists in the repo already which looks pretty reasonable to me. Does it work?

**Comment by jerryuhoo** [comment]
Hi, the CMakeLists works, and I use this for GitHub Actions to build Linux releases. I don't have a Linux computer so I haven't tested it though.

**Comment by baconpaul** [comment]
Yup! @magnetophon i think you can close this

**Comment by magnetophon** [comment]
I should have looked better, not just in the README.
Sorry for the noise!
