### ISSUE TITLE
LV2 version?

### ISSUE THREAD

**Issue by mxmilkiib** [jerryuhoo/Fire#34]
Now JUCE 7 is out, how about an LV2 version of the plugin?

**Comment by jerryuhoo** [comment]
Hmm, I don't know about LV2 plugins. I guess it is for Linux? I don't have a Linux computer to build plugins for Linux though I can do that in GitHub Actions. But it also takes time to write the configuration. You can turn on the LV2 option in projucer to build the plugin by yourself if you are on Linux.

**Comment by mxmilkiib** [comment]
LV2 is very much multiplatform these days. Easiest host to test with is Carla. I'd like to add this to the AUR, for Arch Linux users, along with a few other plugins, once I find the time and energy. Have you considered moving to CMake? I've (briefly) seen Actions using that at least. Thanks for your time anyhow!
